# Generated by Django 3.2.7 on 2021-09-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
